{% set name = "hpp-corbaserver" %}
{% set version = "4.15.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: aafe63d264aa65664efe7c1f296c506e8114449c5d71b44b14cca24bb95b4ff7

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - python                                 # [build_platform != target_platform]
    - pinocchio                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - libboost-devel
    - tinyxml
    - pinocchio
    - hpp-fcl
    - hpp-util  {{ version }}
    - hpp-statistics  {{ version }}
    - hpp-pinocchio  {{ version }}
    - hpp-constraints  {{ version }}
    - hpp-core  {{ version }}
    - hpp-template-corba  {{ version }}
    - omniorb
    - omniorbpy
    - python
  run:
    - tinyxml
    - omniorb
    - omniorbpy
    - python

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]
  imports:
    - hpp

about:
  home: https://github.com/humanoid-path-planner/{{ name }}
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ name }}

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
